### ISSUE TITLE
Number of Dice not working

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-fitdroller#2]
The number of dice don't change on v10
![image](https://user-images.githubusercontent.com/4999783/188511566-8c7c2cdd-5694-46ba-8f03-2c0b6dd81316.png)

**Comment by drewg13** [comment]
Sorry about that, I realized there were some fixes I had queued up, but had not committed or released (or fully completed).  Thanks for the prompt to do so.
