### ISSUE TITLE
New Interface Max Dice

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-fitdroller#3]
Hi.

Can you make the new interface read the max dice?
![image](https://user-images.githubusercontent.com/4999783/188698271-952af34f-4214-4120-9f12-f33fdb1c9968.png)

Some fitd hacks can stack up to 8/9.  (https://matteosciutteri.itch.io/bloodstone)

Tks

**Comment by drewg13** [comment]
Good idea, I wasn't sure the new interface would handle it well, but it did.  Added to next release.

**Comment by brunocalado** [comment]
Thank you.
