### ISSUE TITLE
Setting to Hide Extreme Column

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-fitdroller#4]
Hi!

Can you add an option to hide the extreme column? This is not used in all fitd hacks

![image](https://user-images.githubusercontent.com/4999783/188698538-2f8f0d70-acbe-452d-b13b-ba9dac856b17.png)

**Comment by drewg13** [comment]
More complicated than you might think.  The only thing I couldn't figure out was how to allow the Use Extreme setting to modify the options available to the Default Effect setting, so you can disable Extreme Effect, but still set Extreme as the Default Effect.  I'll think on how to fix it, but it still works OK this way.  Added to next release.
