### ISSUE TITLE
Custom Messages

### ISSUE THREAD

**Issue by brunocalado** [drewg13/foundryvtt-fitdroller#5]
Hi.

Can you let the user input the messages in settings? 

This is useful to easily translate. This is also useful to use fitd hacks.
![image](https://user-images.githubusercontent.com/4999783/188699282-abf5135d-082f-4e22-80ac-507cbb69a707.png)

Tks

**Comment by drewg13** [comment]
This is a very good idea, but quite complex to properly design a UI to handle it.  This is going to take some time to implement.

**Comment by drewg13** [comment]
Finally figured it out, let me know what you think.

**Comment by brunocalado** [comment]
Thank you.
